/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * Modify at your own risk.
 */

package io.vertx.bigquery.model;


import io.vertx.codegen.annotations.DataObject;
import io.vertx.core.json.JsonObject;

/**
 * Model definition for JobStatus.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the BigQuery API. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@DataObject(generateConverter = true)
public final class JobStatus {

  /**
   * [Output-only] Final error result of the job. If present, indicates that the job has completed
   * and was unsuccessful.
   * The value may be {@code null}.
   */
  
  private ErrorProto errorResult;

  /**
   * [Output-only] The first errors encountered during the running of the job. The final message
   * includes the number of errors that caused the process to stop. Errors here do not necessarily
   * mean that the job has completed or was unsuccessful.
   * The value may be {@code null}.
   */
  
  private java.util.List<ErrorProto> errors;


  /**
   * [Output-only] Running state of the job.
   * The value may be {@code null}.
   */
  
  private String state;

  /**
   * [Output-only] Final error result of the job. If present, indicates that the job has completed
   * and was unsuccessful.
   * @return value or {@code null} for none
   */
  public ErrorProto getErrorResult() {
    return errorResult;
  }

  /**
   * [Output-only] Final error result of the job. If present, indicates that the job has completed
   * and was unsuccessful.
   * @param errorResult errorResult or {@code null} for none
   */
  public JobStatus setErrorResult(ErrorProto errorResult) {
    this.errorResult = errorResult;
    return this;
  }

  /**
   * [Output-only] The first errors encountered during the running of the job. The final message
   * includes the number of errors that caused the process to stop. Errors here do not necessarily
   * mean that the job has completed or was unsuccessful.
   * @return value or {@code null} for none
   */
  public java.util.List<ErrorProto> getErrors() {
    return errors;
  }

  /**
   * [Output-only] The first errors encountered during the running of the job. The final message
   * includes the number of errors that caused the process to stop. Errors here do not necessarily
   * mean that the job has completed or was unsuccessful.
   * @param errors errors or {@code null} for none
   */
  public JobStatus setErrors(java.util.List<ErrorProto> errors) {
    this.errors = errors;
    return this;
  }

  /**
   * [Output-only] Running state of the job.
   * @return value or {@code null} for none
   */
  public String getState() {
    return state;
  }

  /**
   * [Output-only] Running state of the job.
   * @param state state or {@code null} for none
   */
  public JobStatus setState(String state) {
    this.state = state;
    return this;
  }
public JobStatus(JsonObject jsonObject) {
	// TODO Auto-generated constructor stub
}
}
