/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * Modify at your own risk.
 */

package io.vertx.bigquery.model;

import io.vertx.codegen.annotations.DataObject;
import io.vertx.core.json.JsonObject;

/**
 * Model definition for ProjectList.
 *
 * <p>
 * This is the Java data model class that specifies how to parse/serialize into
 * the JSON that is transmitted over HTTP when working with the BigQuery API.
 * For a detailed explanation see: <a href=
 * "http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@DataObject(generateConverter = true)
public final class ProjectList {

	/**
	 * A hash of the page of results The value may be {@code null}.
	 */

	private java.lang.String etag;

	/**
	 * The type of list. The value may be {@code null}.
	 */

	private java.lang.String kind;

	/**
	 * A token to request the next page of results. The value may be {@code null}.
	 */

	private java.lang.String nextPageToken;

	/**
	 * Projects to which you have at least READ access. The value may be
	 * {@code null}.
	 */

	private java.util.List<Projects> projects;

	/**
	 * The total number of projects in the list. The value may be {@code null}.
	 */

	private java.lang.Integer totalItems;

	/**
	 * A hash of the page of results
	 * 
	 * @return value or {@code null} for none
	 */
	public java.lang.String getEtag() {
		return etag;
	}

	/**
	 * A hash of the page of results
	 * 
	 * @param etag
	 *            etag or {@code null} for none
	 */
	public ProjectList setEtag(java.lang.String etag) {
		this.etag = etag;
		return this;
	}

	/**
	 * The type of list.
	 * 
	 * @return value or {@code null} for none
	 */
	public java.lang.String getKind() {
		return kind;
	}

	/**
	 * The type of list.
	 * 
	 * @param kind
	 *            kind or {@code null} for none
	 */
	public ProjectList setKind(java.lang.String kind) {
		this.kind = kind;
		return this;
	}

	/**
	 * A token to request the next page of results.
	 * 
	 * @return value or {@code null} for none
	 */
	public java.lang.String getNextPageToken() {
		return nextPageToken;
	}

	/**
	 * A token to request the next page of results.
	 * 
	 * @param nextPageToken
	 *            nextPageToken or {@code null} for none
	 */
	public ProjectList setNextPageToken(java.lang.String nextPageToken) {
		this.nextPageToken = nextPageToken;
		return this;
	}

	/**
	 * Projects to which you have at least READ access.
	 * 
	 * @return value or {@code null} for none
	 */
	public java.util.List<Projects> getProjects() {
		return projects;
	}

	/**
	 * Projects to which you have at least READ access.
	 * 
	 * @param projects
	 *            projects or {@code null} for none
	 */
	public ProjectList setProjects(java.util.List<Projects> projects) {
		this.projects = projects;
		return this;
	}

	/**
	 * The total number of projects in the list.
	 * 
	 * @return value or {@code null} for none
	 */
	public java.lang.Integer getTotalItems() {
		return totalItems;
	}

	/**
	 * The total number of projects in the list.
	 * 
	 * @param totalItems
	 *            totalItems or {@code null} for none
	 */
	public ProjectList setTotalItems(java.lang.Integer totalItems) {
		this.totalItems = totalItems;
		return this;
	}

	/**
	 * Model definition for ProjectListProjects.
	 */

	public ProjectList(JsonObject jsonObject) {
		ProjectListConverter.fromJson(jsonObject, this);
	}

	public JsonObject toJson() {
		JsonObject jsonObject = new JsonObject();
		ProjectListConverter.toJson(this, jsonObject);
		return jsonObject;
	}
}
