/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * Modify at your own risk.
 */

package io.vertx.bigquery.model;

import io.vertx.codegen.annotations.DataObject;
import io.vertx.core.json.JsonObject;

/**
 * Model definition for QueryParameterType.
 *
 * <p>
 * This is the Java data model class that specifies how to parse/serialize into
 * the JSON that is transmitted over HTTP when working with the BigQuery API.
 * For a detailed explanation see: <a href=
 * "http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@DataObject(generateConverter = true)
public final class QueryParameterType {

	/**
	 * [Optional] The type of the array's elements, if this is an array. The value
	 * may be {@code null}.
	 */
	
	private QueryParameterType arrayType;

	/**
	 * [Optional] The types of the fields of this struct, in order, if this is a
	 * struct. The value may be {@code null}.
	 */
	
	private java.util.List<StructTypes> structTypes;

	/**
	 * [Required] The top level type of this field. The value may be {@code null}.
	 */
	
	private java.lang.String type;

	/**
	 * [Optional] The type of the array's elements, if this is an array.
	 * 
	 * @return value or {@code null} for none
	 */
	public QueryParameterType getArrayType() {
		return arrayType;
	}

	/**
	 * [Optional] The type of the array's elements, if this is an array.
	 * 
	 * @param arrayType
	 *            arrayType or {@code null} for none
	 */
	public QueryParameterType setArrayType(QueryParameterType arrayType) {
		this.arrayType = arrayType;
		return this;
	}

	/**
	 * [Optional] The types of the fields of this struct, in order, if this is a
	 * struct.
	 * 
	 * @return value or {@code null} for none
	 */
	public java.util.List<StructTypes> getStructTypes() {
		return structTypes;
	}

	/**
	 * [Optional] The types of the fields of this struct, in order, if this is a
	 * struct.
	 * 
	 * @param structTypes
	 *            structTypes or {@code null} for none
	 */
	public QueryParameterType setStructTypes(java.util.List<StructTypes> structTypes) {
		this.structTypes = structTypes;
		return this;
	}

	/**
	 * [Required] The top level type of this field.
	 * 
	 * @return value or {@code null} for none
	 */
	public java.lang.String getType() {
		return type;
	}

	/**
	 * [Required] The top level type of this field.
	 * 
	 * @param type
	 *            type or {@code null} for none
	 */
	public QueryParameterType setType(java.lang.String type) {
		this.type = type;
		return this;
	}

	/**
	 * Model definition for QueryParameterTypeStructTypes.
	 */


	public QueryParameterType(JsonObject jsonObject) {
		// TODO Auto-generated constructor stub
	}
}
