/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * Modify at your own risk.
 */

package io.vertx.bigquery.model;

import io.vertx.codegen.annotations.DataObject;
import io.vertx.core.json.JsonObject;

/**
 * Model definition for Streamingbuffer.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the BigQuery API. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@DataObject(generateConverter = true)
public final class Streamingbuffer  {

  /**
   * [Output-only] A lower-bound estimate of the number of bytes currently in the streaming buffer.
   * The value may be {@code null}.
   */

  private java.math.BigInteger estimatedBytes;

  /**
   * [Output-only] A lower-bound estimate of the number of rows currently in the streaming buffer.
   * The value may be {@code null}.
   */

  private java.math.BigInteger estimatedRows;

  /**
   * [Output-only] Contains the timestamp of the oldest entry in the streaming buffer, in
   * milliseconds since the epoch, if the streaming buffer is available.
   * The value may be {@code null}.
   */

  private java.math.BigInteger oldestEntryTime;

  /**
   * [Output-only] A lower-bound estimate of the number of bytes currently in the streaming buffer.
   * @return value or {@code null} for none
   */
  public java.math.BigInteger getEstimatedBytes() {
    return estimatedBytes;
  }

  /**
   * [Output-only] A lower-bound estimate of the number of bytes currently in the streaming buffer.
   * @param estimatedBytes estimatedBytes or {@code null} for none
   */
  public Streamingbuffer setEstimatedBytes(java.math.BigInteger estimatedBytes) {
    this.estimatedBytes = estimatedBytes;
    return this;
  }

  /**
   * [Output-only] A lower-bound estimate of the number of rows currently in the streaming buffer.
   * @return value or {@code null} for none
   */
  public java.math.BigInteger getEstimatedRows() {
    return estimatedRows;
  }

  /**
   * [Output-only] A lower-bound estimate of the number of rows currently in the streaming buffer.
   * @param estimatedRows estimatedRows or {@code null} for none
   */
  public Streamingbuffer setEstimatedRows(java.math.BigInteger estimatedRows) {
    this.estimatedRows = estimatedRows;
    return this;
  }

  /**
   * [Output-only] Contains the timestamp of the oldest entry in the streaming buffer, in
   * milliseconds since the epoch, if the streaming buffer is available.
   * @return value or {@code null} for none
   */
  public java.math.BigInteger getOldestEntryTime() {
    return oldestEntryTime;
  }

  /**
   * [Output-only] Contains the timestamp of the oldest entry in the streaming buffer, in
   * milliseconds since the epoch, if the streaming buffer is available.
   * @param oldestEntryTime oldestEntryTime or {@code null} for none
   */
  public Streamingbuffer setOldestEntryTime(java.math.BigInteger oldestEntryTime) {
    this.oldestEntryTime = oldestEntryTime;
    return this;
  }
public Streamingbuffer(JsonObject jsonObject) {
	// TODO Auto-generated constructor stub
}
}
